name: Auto Compress
on:
  workflow_call:  # ให้ workflow อื่นเรียกใช้ได้
    inputs:
      quality:
        required: false
        type: string
        default: '85'

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: ${{ inputs.quality }}
